### ISSUE TITLE
Feature Request: Debug Mode

### ISSUE THREAD

**Issue by IBMRob** [ReverseEngineeringDE/iSmart-Gateway-Home-Assistant-Add-on#9]
It would be great if there was a way of enabling debug mode so that we could see all the response from the API enabling us to see which options are available for a given car (i.e. I am using it against an MG4 which may have different options)

**Comment by IBMRob** [comment]
Closing this as it looks like the debug on the configuration page should provide what's needed here i.e in configuration add
```
logger:
  default: info
  logs:
    homeassistant.components.rest: debug
```
